package com.twadeclark.tailwindtrader;

public interface TradingStrategy {
    /**
     * Execute the trading strategy based on the provided market data.
     *
     * @param security the ticker for the security
     * @param sw the strategy parameters
     * @param circularBuffer the chart for the current security
     * @return A TradeSignal object representing the trading signal generated by the strategy.
     */
    TradeSignal execute(String security, StrategyWrapper sw, CircularBuffer<StockData> circularBuffer);
}

